ci: add docker build smoke test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,6 +6,7 @@ on:
     branches:
       # Push events on the main branch
       - main
+      - CTIA-15-verify-docker-images
 
 env:
   PKG_NAME: consul
@@ -244,3 +245,11 @@ jobs:
           dev_tags: |
             docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-dev
             docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-${{ github.sha }}
+          smoke_test: |
+            TEST_VERSION="$(docker run "${IMAGE_NAME}" version  | head -n1 | awk '{print $2}')"
+            if [ "${TEST_VERSION}" != "v${version}" ]; then
+              echo "Test FAILED"
+              echo "Got: ${TEST_VERSION}, Want: ${version}"
+              exit 1
+            fi
+            echo "Test PASSED"
