have arm64 use reusable-unit

diff --git a/.github/workflows/go-tests.yml b/.github/workflows/go-tests.yml
--- a/.github/workflows/go-tests.yml
+++ b/.github/workflows/go-tests.yml
@@ -105,94 +105,106 @@ jobs:
     with:
       go-arch: "386"
 
-  go-test-arm64:
-    # TODO(JM):  Fix to run on arm64
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
-      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
-        with:
-          go-version-file: 'go.mod'
-      - name: Install gotestsum
-        run: |
-          wget https://github.com/gotestyourself/gotestsum/releases/download/v${{env.GOTESTSUM_VERSION}}/gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
-          sudo tar -C /usr/local/bin -xzf gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
-          rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
-      - run: go mod download
-      - name: make dev
-        run: |
-          # TODO(JM)- figure out why this is only needed on these branches
-          # if [[ '${{ github.ref }}' == 'refs/heads/main' || startsWith('${{ github.ref }}', 'refs/heads/release/') ]]; then
-            make dev
-          # fi
-      # TODO(JM)- if not always building above, re-enable this.
-      # - uses: actions/download-artifact@v3
-      #   with:
-      #     name: consul-bin
-      #     path: ./bin/consul
-      - run: go mod download
-      - name: go test
-        run: |
-            PACKAGE_NAMES=$(go list ./...)
-            
-            # TODO(JM): figure out why this erroring
-            # if [[ github.ref == 'refs/heads/main' || !startsWith(github.ref, 'refs/heads/release/') ]]; then
-            #   export GO_TEST_FLAGS="-short"
-            # fi
-            
-            # some tests expect this umask, and arm images have a different default
-            umask 0022
-
-            gotestsum \
-            --format=short-verbose \
-            --jsonfile /tmp/jsonfile/go-test-${CIRCLE_NODE_INDEX}.log \
-            --debug \
-            --rerun-fails=3 \
-            --rerun-fails-max-failures=40 \
-            --rerun-fails-report=/tmp/gotestsum-rerun-fails \
-            --packages="$PACKAGE_NAMES" \              
-            --junitfile ${{env.TEST_RESULTS}}/gotestsum-report.xml -- \
-            -tags="$GOTAGS" -p 4 \
-            ${GO_TEST_FLAGS-} \
-            -cover -coverprofile=coverage.txt
-      - uses: actions/upload-artifact@master
-        with:
-          name: test-results
-          path: ${{env.TEST_RESULTS}}
-      - uses: actions/upload-artifact@master
-        with:
-          name: jsonfile
-          path: /tmp/jsonfile
-      # - name: "Re-run fails report"
-      #   run: |
-      #     #!/usr/bin/env bash
-      #     #
-      #     # Add a comment on the github PR if there were any rerun tests.
-      #     #
-      #     set -eu -o pipefail
-
-      #     report_filename="${1?report filename is required}"
-      #     if [ ! -s "$report_filename" ]; then
-      #         echo "gotestsum rerun report file is empty or missing"
-      #         exit 0
-      #     fi
-
-      #     function report {
-      #         echo ":repeat: gotestsum re-ran some tests in $CIRCLE_BUILD_URL"
-      #         echo
-      #         echo '```'
-      #         cat "$report_filename"
-      #         echo '```'
-      #     }
-
-      #     report
-      - name: Notify Slack
-        if: failure()
-        run: .github/scripts/notify_slack.sh
-
   # create a development build
   dev-build:
     uses: ./.github/workflows/reusable-dev-build.yml
+
+  # create a development build for arm64
+  dev-build-arm64:
+    uses: ./.github/workflows/reusable-dev-build.yml
+    with:
+      uploaded-binary-name: 'consul-bin-arm64'
+
+  go-test-arm64:
+    # TODO(JM):  Fix to run on arm64
+    runs-on: ubuntu-latest
+    needs: [dev-build-arm64]
+    uses: ./.github/workflows/reusable-unit.yml
+    with:
+      directory: .
+      go-version: "1.20"
+      uploaded-binary-name: 'consul-bin-arm64'
+    # steps:
+    #   - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
+    #   - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
+    #     with:
+    #       go-version-file: 'go.mod'
+    #   - name: Install gotestsum
+    #     run: |
+    #       wget https://github.com/gotestyourself/gotestsum/releases/download/v${{env.GOTESTSUM_VERSION}}/gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
+    #       sudo tar -C /usr/local/bin -xzf gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
+    #       rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
+    #   - run: go mod download
+    #   - name: make dev
+    #     run: |
+    #       # TODO(JM)- figure out why this is only needed on these branches
+    #       # if [[ '${{ github.ref }}' == 'refs/heads/main' || startsWith('${{ github.ref }}', 'refs/heads/release/') ]]; then
+    #         make dev
+    #       # fi
+    #   # TODO(JM)- if not always building above, re-enable this.
+    #   # - uses: actions/download-artifact@v3
+    #   #   with:
+    #   #     name: consul-bin
+    #   #     path: ./bin/consul
+    #   - run: go mod download
+    #   - name: go test
+    #     run: |
+    #         PACKAGE_NAMES=$(go list ./...)
+            
+    #         # TODO(JM): figure out why this erroring
+    #         # if [[ github.ref == 'refs/heads/main' || !startsWith(github.ref, 'refs/heads/release/') ]]; then
+    #         #   export GO_TEST_FLAGS="-short"
+    #         # fi
+            
+    #         # some tests expect this umask, and arm images have a different default
+    #         umask 0022
+
+    #         gotestsum \
+    #         --format=short-verbose \
+    #         --jsonfile /tmp/jsonfile/go-test-${CIRCLE_NODE_INDEX}.log \
+    #         --debug \
+    #         --rerun-fails=3 \
+    #         --rerun-fails-max-failures=40 \
+    #         --rerun-fails-report=/tmp/gotestsum-rerun-fails \
+    #         --packages="$PACKAGE_NAMES" \              
+    #         --junitfile ${{env.TEST_RESULTS}}/gotestsum-report.xml -- \
+    #         -tags="$GOTAGS" -p 4 \
+    #         ${GO_TEST_FLAGS-} \
+    #         -cover -coverprofile=coverage.txt
+    #   - uses: actions/upload-artifact@master
+    #     with:
+    #       name: test-results
+    #       path: ${{env.TEST_RESULTS}}
+    #   - uses: actions/upload-artifact@master
+    #     with:
+    #       name: jsonfile
+    #       path: /tmp/jsonfile
+    #   # - name: "Re-run fails report"
+    #   #   run: |
+    #   #     #!/usr/bin/env bash
+    #   #     #
+    #   #     # Add a comment on the github PR if there were any rerun tests.
+    #   #     #
+    #   #     set -eu -o pipefail
+
+    #   #     report_filename="${1?report filename is required}"
+    #   #     if [ ! -s "$report_filename" ]; then
+    #   #         echo "gotestsum rerun report file is empty or missing"
+    #   #         exit 0
+    #   #     fi
+
+    #   #     function report {
+    #   #         echo ":repeat: gotestsum re-ran some tests in $CIRCLE_BUILD_URL"
+    #   #         echo
+    #   #         echo '```'
+    #   #         cat "$report_filename"
+    #   #         echo '```'
+    #   #     }
+
+    #   #     report
+    #   - name: Notify Slack
+    #     if: failure()
+    #     run: .github/scripts/notify_slack.sh
 
   go-test:
     needs:
@@ -221,8 +233,6 @@ jobs:
           rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
 
       - run:  mkdir -p ${{env.TEST_RESULTS}}
-      - run:  echo "$HOME/bin" >> $GITHUB_PATH
-
       # - name: Download consul
       #   run: |
       #     mkdir -p $HOME/bin
